import path from 'path';
import packageJson from '../package.json';
import type { DotConfigEnvironment } from './types/index';

const header = `/**
 * This file is generated by dotconfig. Do not edit it directly.
 * Instead, edit the dotconfig.js or dotconfig.ts file in your project root.
 *
 * See https://github.com/gas-buddy/dotconfig for more information.
 * @version dotconfig@${packageJson.version}
 */
`;

export const headerMarker = 'This file is generated by dotconfig. Do not edit it directly';

function leadingDot(filename: string) {
  return filename.startsWith('.') ? filename : `./${filename}`;
}

export function getFile(
  env: DotConfigEnvironment,
  key: string,
  filename: string,
) {
  const relative = leadingDot(path.relative(path.dirname(env.packagePath), env.dotconfigPath));
  const noExt = relative.substring(0, relative.length - path.extname(relative).length);
  if (path.extname(filename) === '.ts') {
    return `${header}import { '${key}' as config } from '${noExt}';
const resolved = typeof config === 'function' ? config() : config;
export default resolved;\n`;
  }
  if (path.extname(env.dotconfigPath) === '.ts') {
    return `${header}
require('ts-node').register();
const config = require('${noExt}').default['${key}'].configuration;
module.exports = typeof config === 'function' ? config() : config;\n`;
  }
  return `${header}
const raw = require('${noExt}').default['${key}'].configuration;
const config = typeof config === 'function' ? config() : config;
module.exports = config;\n`;
}
