import path from 'path';
import packageJson from '../package.json';
import type { CoConfigEnvironment } from './types/index';

const header = `/**
 * This file is generated by coconfig. Do not edit it directly.
 * Instead, edit the coconfig.js or coconfig.ts file in your project root.
 *
 * See https://github.com/gas-buddy/coconfig for more information.
 * @version coconfig@${packageJson.version}
 */`;

export const headerMarker = 'This file is generated by coconfig. Do not edit it directly';

function leadingDot(filename: string) {
  return filename.startsWith('.') ? filename : `./${filename}`;
}

export function getFile(
  env: CoConfigEnvironment,
  key: string,
  filename: string,
) {
  const relative = leadingDot(path.relative(path.dirname(env.packagePath), env.coconfigPath));
  const noExt = relative.substring(0, relative.length - path.extname(relative).length);
  if (path.extname(filename) === '.ts') {
    return `${header}import { '${key}' as config } from '${noExt}';
const resolved = typeof config === 'function' ? config() : config;
export default resolved;\n`;
  }
  if (path.extname(env.coconfigPath) === '.ts') {
    return `${header}
require('ts-node').register();
const config = require('${noExt}').default['${key}'].configuration;
module.exports = typeof config === 'function' ? config() : config;\n`;
  }
  return `${header}
const raw = require('${noExt}').default['${key}'].configuration;

const config = typeof raw === 'function' ? raw() : raw;
module.exports = config;\n`;
}
